#spring config
spring:
  application:
    name: api-getaway
  cloud:
    gateway:
     discovery:
       locator:
         enabled: true
     routes:
      - id: ms-business-partner
        uri: lb://ms-business-partner
        predicates:
          - Path=/BusinessPartnerService/**
      - id: ms-account-service
        uri: lb://ms-account-service
        predicates:
          - Path=/Accounts/**
      - id: ms-credit-service
        uri: lb://ms-credit-service
        predicates:
          - Path=/Credits/**
      - id: ms-yanki-service
        uri: lb://ms-yanki-service
        predicates:
            - Path=/YankiMobile/**
      - id: ms-bootcoin-service
        uri: lb://ms-bootcoin-service
        predicates:
            - Path=/BootCoin/**
#server config  
server:
  port: 8080
#eureka config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
    enabled: true
  instance:
    hostname: localhost

  