#spring config
spring:
  data:
      mongodb:
        uri: mongodb+srv://trainingdbnttdata:zMaT0bwJ86xps4wN@proyectobootcamp.jyiov.mongodb.net/bspartners
  application:
    name: ms-business-partner
#server config
server:
  port: 8080
#eureka config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://registry-service-ws.azurewebsites.net/eureka/
    enabled: true
  instance:
    hostname: localhost